const path = require('path');

module.exports = {
  entry: {
    'js/index': './src/scripts/index', // generates index.js inside dist/js folder
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].bundle.js',
  },
  devServer: {
    // Serve this folder
    contentBase: path.join(__dirname, 'dist'),
    // overlay: true,
  },
  devtool: 'source-map',
  module: {
    rules: [
      // Sass and CSS
      {
        test: /\.s?css/,
        use: ['style-loader', 'css-loader', 'sass-loader'],
      },
      // For HTML (This will also update all relative paths such as paths to inline images accourdingly)
      {
        test: /\.html$/,
        use: [
          {
            // Creates an html file and update all relative paths inside the html file
            loader: 'file-loader',
            options: { name: '[name].html' },
          },
          {
            // Extract the HTML code stored in the string generated by html-loader
            loader: 'extract-loader',
          },
          {
            // Get the HTML code and save in a string
            loader: 'html-loader',
          },
        ],
      },
      // Copy all images to dist folder and minify them
      {
        test: /\.(gif|png|jpe?g)$/i,
        use: [
          // Copies all inline and background-images to dist/images folder
          {
            loader: 'file-loader',
            options: { name: '[name].[hash][ext]', outputPath: 'images/' },
          },

          // Minify PNG, JPEG, GIF, SVG and WEBP images with imagemin
          {
            loader: 'image-webpack-loader',
            options: {
              mozjpeg: {
                progressive: true,
                quality: 65,
              },
              // optipng.enabled: false will disable optipng
              optipng: {
                enabled: false,
              },
              pngquant: {
                quality: '65-90',
                speed: 4,
              },
              gifsicle: {
                interlaced: false,
              },
            },
          },
        ],
      },
    ],
  },
};
